# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DJabberd-RosterStorage-SQLite-Fixed
version:      0.02
version_from: lib/DJabberd/RosterStorage/SQLite/Fixed.pm
installdirs:  site
requires:
    DJabberd:                      0.83
    DJabberd::RosterStorage::SQLite: 1
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
